"""End-to-end integration test for the voice package.

Drives a real WAV file (generated by macOS ``say`` and committed
to ``tests/fixtures/say_cat.wav``) through the full pipeline:
WavFileCapture → stream_audio_request_body → fake provider that
captures the wire bytes → assert the bytes round-trip back to
the original WAV.

The fixture WAV says "set my display to a picture of a cat" at
16kHz mono int16 — exactly the shape the chip's I2S PDM mic
produces. So this test catches any wiring bug between the
capture iterator and the audio model's expected payload format
that a synthetic-bytes test wouldn't hit.

Generated via:

    say -o say_cat.wav --data-format=LEI16@16000 \\
        "set my display to a picture of a cat"
"""

from __future__ import annotations

import base64
import json
import os
from typing import AsyncIterator

import pytest
from exoclaw_tools_voice import (
    AudioCapabilities,
    ListenAndTranscribeTool,
    stream_audio_request_body,
)

_FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures", "say_cat.wav")


class _FileCapture:
    """File-backed ``AudioCapture``. Mirrors
    ``boards/unix/audio.py``'s ``WavFileCapture`` but inlined
    here so the voice package's tests don't need the firmware
    tree on the Python path."""

    def __init__(self, path: str, chunk: int = 3072) -> None:
        self._path = path
        self._chunk = chunk
        self.capabilities = AudioCapabilities(
            sample_rate_hz=16000,
            bit_depth=16,
            channels=1,
            format="wav",
        )

    def listen(
        self,
        max_duration_s: float,
        silence_threshold: int,
        silence_seconds: float,
    ) -> AsyncIterator[bytes]:
        return self._iter()

    async def _iter(self) -> AsyncIterator[bytes]:
        with open(self._path, "rb") as f:
            while True:
                buf = f.read(self._chunk)
                if not buf:
                    break
                yield buf


class _CapturingProvider:
    """Drains the streaming body the tool produces, returns a
    fixed transcription. Lets the test verify the wire bytes
    without hitting OpenRouter."""

    def __init__(self) -> None:
        self.body_bytes: bytes | None = None

    async def send_streaming_body(self, model: str, body: AsyncIterator[bytes]) -> str:
        out = bytearray()
        async for chunk in body:
            out.extend(chunk)
        self.body_bytes = bytes(out)
        return "set my display to a picture of a cat."


@pytest.mark.asyncio
async def test_real_wav_through_pipeline_round_trips_to_base64() -> None:
    """The ``say``-generated WAV bytes, fed through
    WavFileCapture → streaming body → base64 encoder, should
    decode back to exactly the WAV file's bytes. If any chunk
    boundary corrupts data this test catches it deterministically."""
    capture = _FileCapture(_FIXTURE)
    provider = _CapturingProvider()
    tool = ListenAndTranscribeTool(
        provider=provider,  # type: ignore[invalid-argument-type]
        capture=capture,
        audio_model="openai/gpt-audio-mini",
    )

    out = await tool.execute()
    assert out == "set my display to a picture of a cat."
    assert provider.body_bytes is not None

    # Round-trip the base64 portion of the JSON body back to bytes.
    parsed = json.loads(provider.body_bytes.decode("utf-8"))
    audio_part = parsed["messages"][0]["content"][1]
    decoded = base64.b64decode(audio_part["input_audio"]["data"])

    with open(_FIXTURE, "rb") as f:
        original = f.read()
    assert decoded == original, "round-trip mismatch: {} bytes in, {} out".format(
        len(original), len(decoded)
    )


@pytest.mark.asyncio
async def test_streaming_body_with_real_wav_handles_chip_chunk_size() -> None:
    """Chip-realistic chunk size (3072 = 1024 int16 samples =
    64ms @ 16kHz). The WAV is ~73KB so we expect ~24 audio
    chunks plus envelope frames — verifies the streaming pattern
    actually fires multiple times rather than buffering the whole
    file."""
    capture = _FileCapture(_FIXTURE, chunk=3072)
    body_gen = stream_audio_request_body(
        model="openai/gpt-audio-mini",
        user_text="Transcribe.",
        audio_chunks=capture.listen(15.0, 500, 1.5),
        audio_format="wav",
        max_tokens=64,
        temperature=0.0,
    )
    chunks: list[bytes] = []
    async for c in body_gen:
        chunks.append(c)
    # 73KB WAV / 3072-byte chunks ≈ 24 audio yields. Add envelope
    # head + prefix + trailing close. Anything below 20 means the
    # streaming collapsed.
    assert len(chunks) > 20, "expected ~25 chunks, got {}".format(len(chunks))
